# ----------------------------------------------------------------------------------------
# CONFIGMAP — Stores configuration values for the Payment microservice.
#
# Payment interacts with:
# ✔ Cart service  → to fetch cart details
# ✔ User service  → to get user information
# ✔ RabbitMQ      → to publish payment events (AMQP)
#
# These values are injected into the pod as environment variables.
# ----------------------------------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
data:
  CART_HOST: "cart"
  CART_PORT: "8080"

  USER_HOST: "user"
  USER_PORT: "8080"

  AMQP_HOST: "rabbitmq"          # RabbitMQ internal service DNS
  AMQP_USER: "roboshop"          # Default RabbitMQ username
  AMQP_PASS: "roboshop123"       # Default RabbitMQ password

---
# ----------------------------------------------------------------------------------------
# DEPLOYMENT — Manages the Payment backend service pods.
#
# Ensures:
# ✔ Desired number of replicas
# ✔ Rolling updates
# ✔ Automatic pod restart when failed
# ✔ Works with HPA for auto scaling
# ----------------------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop

  # Deployment-level labels
  labels:
    project: roboshop
    component: payment
    tier: backend

spec:
  replicas: 1   # Only 1 to start; autoscaler will adjust based on load

  selector:
    matchLabels:
      project: roboshop
      component: payment
      tier: backend

  # -------------------------------------
  # POD TEMPLATE — Defines container details
  # -------------------------------------
  template:
    metadata:
      labels:
        project: roboshop
        component: payment
        tier: backend

    spec:
      containers:
      - name: payment
        image: arjunaws/payment:v1
        imagePullPolicy: Always    # Always pull latest version when updating deployment

        # Load all environment variables from ConfigMap
        envFrom:
        - configMapRef:
            name: payment

        ports:
        - name: liveness-port
          containerPort: 8080       # Payment service listens on port 8080

        # -------------------------------------
        # RESOURCE REQUESTS & LIMITS
        #
        # requests → minimum guaranteed resources
        # limits   → maximum allowed resources
        # -------------------------------------
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"

        # -------------------------------------
        # READINESS PROBE
        #
        # Ensures pod receives traffic ONLY when healthy & ready.
        # -------------------------------------
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15

        # -------------------------------------
        # LIVENESS PROBE
        #
        # Automatically restarts container if it becomes unhealthy.
        # -------------------------------------
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15

---
# ----------------------------------------------------------------------------------------
# SERVICE — Provides stable DNS and load-balanced access to Payment service.
#
# Other services call it using:
#   payment.roboshop.svc.cluster.local:8080
# ----------------------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: payment
    tier: backend

  ports:
    - protocol: TCP
      port: 8080      # Service port
      targetPort: 8080 # Container port

---
# ----------------------------------------------------------------------------------------
# HORIZONTAL POD AUTOSCALER (HPA)
# Autoscaling based on CPU load.
#
# If CPU usage > 5% (real world = 70%):
#    HPA will create additional Payment pods.
#
# If traffic decreases:
#    Autoscaler reduces pod count.
# ----------------------------------------------------------------------------------------
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    component: payment
    tier: backend

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment

  minReplicas: 1      # Minimum 1 replica always
  maxReplicas: 10     # Scale up to 10 pods during peak traffic

  metrics:
  - type: Resource    # CPU based scaling
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 5  # Real value → 70%
